
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: false
})

module.exports = {
  reactStrictMode: false,
  transpilePackages: ['@mui/x-charts'],
  // output: "export",
  env: {
    NEXT_PUBLIC_REPORTS_URL: process.env.NEXT_PUBLIC_REPORTS_URL,
    NEXT_PUBLIC_NODE_BACKEND_URL: process.env.NEXT_PUBLIC_NODE_BACKEND_URL,
    NEXT_PUBLIC_MESSAGES_URL: process.env.NEXT_PUBLIC_MESSAGES_URL,
    NEXT_PUBLIC_NODE_SOCKET_IO: process.env.NEXT_PUBLIC_NODE_SOCKET_IO,
    NEXT_PUBLIC_PAYMENT_URL: process.env.NEXT_PUBLIC_PAYMENT_URL,
    NEXT_PUBLIC_MERCADOPAGO_CALLBACK_URL: process.env.NEXT_PUBLIC_MERCADOPAGO_CALLBACK_URL,

    NEXT_PUBLIC_REPORTS_URL_PRODUCTION: process.env.NEXT_PUBLIC_REPORTS_URL_PRODUCTION,
    NEXT_PUBLIC_NODE_BACKEND_URL_PRODUCTION: process.env.NEXT_PUBLIC_NODE_BACKEND_URL_PRODUCTION,
    NEXT_PUBLIC_MESSAGES_URL_PRODUCTION: process.env.NEXT_PUBLIC_MESSAGES_URL_PRODUCTION,
    NEXT_PUBLIC_NODE_SOCKET_IO_PRODUCTION: process.env.NEXT_PUBLIC_NODE_SOCKET_IO_PRODUCTION,
    NEXT_PUBLIC_PAYMENT_URL_PRODUCTION: process.env.NEXT_PUBLIC_PAYMENT_URL_PRODUCTION,
    NEXT_PUBLIC_MERCADOPAGO_CALLBACK_URL_PRODUCTION: process.env.NEXT_PUBLIC_MERCADOPAGO_CALLBACK_URL_PRODUCTION,

    NEXT_PUBLIC_ENV_MODE: process.env.NEXT_PUBLIC_ENV_MODE,

    NEXT_PUBLIC_S3_ASSETS_NAME: process.env.NEXT_PUBLIC_S3_ASSETS_NAME,
    NEXT_PUBLIC_S3_ASSETS_REGION: process.env.NEXT_PUBLIC_S3_ASSETS_REGION,
    NEXT_PUBLIC_S3_IDENTITY_POOL_ID: process.env.NEXT_PUBLIC_S3_IDENTITY_POOL_ID,
  }
}

// module.exports = {
//   reactStrictMode: false,
//   transpilePackages: ['@mui/x-charts'],
//   // output: "export",
//   env: {
//     NEXT_REPORTS_URL: process.env.NEXT_REPORTS_URL,
//     NEXT_PUBLIC_NODE_BACKEND_URL: process.env.NEXT_PUBLIC_NODE_BACKEND_URL,
//     NEXT_MESSAGES_URL: process.env.NEXT_MESSAGES_URL,
//   }
// };
