
// From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
const world = [
  { name: 'AD', label: 'Andorra', phone: '376' },
  {
    name: 'AE',
    label: 'United Arab Emirates',
    phone: '971',
  },
  { name: 'AF', label: 'Afghanistan', phone: '93' },
  {
    name: 'AG',
    label: 'Antigua and Barbuda',
    phone: '1-268',
  },
  { name: 'AI', label: 'Anguilla', phone: '1-264' },
  { name: 'AL', label: 'Albania', phone: '355' },
  { name: 'AM', label: 'Armenia', phone: '374' },
  { name: 'AO', label: 'Angola', phone: '244' },
  { name: 'AQ', label: 'Antarctica', phone: '672' },
  { name: 'AR', label: 'Argentina', phone: '54' },
  { name: 'AS', label: 'American Samoa', phone: '1-684' },
  { name: 'AT', label: 'Austria', phone: '43' },
  {
    name: 'AU',
    label: 'Australia',
    phone: '61',
    suggested: true,
  },
  { name: 'AW', label: 'Aruba', phone: '297' },
  { name: 'AX', label: 'Alland Islands', phone: '358' },
  { name: 'AZ', label: 'Azerbaijan', phone: '994' },
  {
    name: 'BA',
    label: 'Bosnia and Herzegovina',
    phone: '387',
  },
  { name: 'BB', label: 'Barbados', phone: '1-246' },
  { name: 'BD', label: 'Bangladesh', phone: '880' },
  { name: 'BE', label: 'Belgium', phone: '32' },
  { name: 'BF', label: 'Burkina Faso', phone: '226' },
  { name: 'BG', label: 'Bulgaria', phone: '359' },
  { name: 'BH', label: 'Bahrain', phone: '973' },
  { name: 'BI', label: 'Burundi', phone: '257' },
  { name: 'BJ', label: 'Benin', phone: '229' },
  { name: 'BL', label: 'Saint Barthelemy', phone: '590' },
  { name: 'BM', label: 'Bermuda', phone: '1-441' },
  { name: 'BN', label: 'Brunei Darussalam', phone: '673' },
  { name: 'BO', label: 'Bolivia', phone: '591' },
  { name: 'BR', label: 'Brazil', phone: '55' },
  { name: 'BS', label: 'Bahamas', phone: '1-242' },
  { name: 'BT', label: 'Bhutan', phone: '975' },
  { name: 'BV', label: 'Bouvet Island', phone: '47' },
  { name: 'BW', label: 'Botswana', phone: '267' },
  { name: 'BY', label: 'Belarus', phone: '375' },
  { name: 'BZ', label: 'Belize', phone: '501' },
  {
    name: 'CA',
    label: 'Canada',
    phone: '1',
    suggested: true,
  },
  {
    name: 'CC',
    label: 'Cocos (Keeling) Islands',
    phone: '61',
  },
  {
    name: 'CD',
    label: 'Congo, Democratic Republic of the',
    phone: '243',
  },
  {
    name: 'CF',
    label: 'Central African Republic',
    phone: '236',
  },
  {
    name: 'CG',
    label: 'Congo, Republic of the',
    phone: '242',
  },
  { name: 'CH', label: 'Switzerland', phone: '41' },
  { name: 'CI', label: "Cote d'Ivoire", phone: '225' },
  { name: 'CK', label: 'Cook Islands', phone: '682' },
  { name: 'CL', label: 'Chile', phone: '56' },
  { name: 'CM', label: 'Cameroon', phone: '237' },
  { name: 'CN', label: 'China', phone: '86' },
  { name: 'CO', label: 'Colombia', phone: '57' },
  { name: 'CR', label: 'Costa Rica', phone: '506' },
  { name: 'CU', label: 'Cuba', phone: '53' },
  { name: 'CV', label: 'Cape Verde', phone: '238' },
  { name: 'CW', label: 'Curacao', phone: '599' },
  { name: 'CX', label: 'Christmas Island', phone: '61' },
  { name: 'CY', label: 'Cyprus', phone: '357' },
  { name: 'CZ', label: 'Czech Republic', phone: '420' },
  {
    name: 'DE',
    label: 'Germany',
    phone: '49',
    suggested: true,
  },
  { name: 'DJ', label: 'Djibouti', phone: '253' },
  { name: 'DK', label: 'Denmark', phone: '45' },
  { name: 'DM', label: 'Dominica', phone: '1-767' },
  {
    name: 'DO',
    label: 'Dominican Republic',
    phone: '1-809',
  },
  { name: 'DZ', label: 'Algeria', phone: '213' },
  { name: 'EC', label: 'Ecuador', phone: '593' },
  { name: 'EE', label: 'Estonia', phone: '372' },
  { name: 'EG', label: 'Egypt', phone: '20' },
  { name: 'EH', label: 'Western Sahara', phone: '212' },
  { name: 'ER', label: 'Eritrea', phone: '291' },
  { name: 'ES', label: 'Spain', phone: '34' },
  { name: 'ET', label: 'Ethiopia', phone: '251' },
  { name: 'FI', label: 'Finland', phone: '358' },
  { name: 'FJ', label: 'Fiji', phone: '679' },
  {
    name: 'FK',
    label: 'Falkland Islands (Malvinas)',
    phone: '500',
  },
  {
    name: 'FM',
    label: 'Micronesia, Federated States of',
    phone: '691',
  },
  { name: 'FO', label: 'Faroe Islands', phone: '298' },
  {
    name: 'FR',
    label: 'France',
    phone: '33',
    suggested: true,
  },
  { name: 'GA', label: 'Gabon', phone: '241' },
  { name: 'GB', label: 'United Kingdom', phone: '44' },
  { name: 'GD', label: 'Grenada', phone: '1-473' },
  { name: 'GE', label: 'Georgia', phone: '995' },
  { name: 'GF', label: 'French Guiana', phone: '594' },
  { name: 'GG', label: 'Guernsey', phone: '44' },
  { name: 'GH', label: 'Ghana', phone: '233' },
  { name: 'GI', label: 'Gibraltar', phone: '350' },
  { name: 'GL', label: 'Greenland', phone: '299' },
  { name: 'GM', label: 'Gambia', phone: '220' },
  { name: 'GN', label: 'Guinea', phone: '224' },
  { name: 'GP', label: 'Guadeloupe', phone: '590' },
  { name: 'GQ', label: 'Equatorial Guinea', phone: '240' },
  { name: 'GR', label: 'Greece', phone: '30' },
  {
    name: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  { name: 'GT', label: 'Guatemala', phone: '502' },
  { name: 'GU', label: 'Guam', phone: '1-671' },
  { name: 'GW', label: 'Guinea-Bissau', phone: '245' },
  { name: 'GY', label: 'Guyana', phone: '592' },
  { name: 'HK', label: 'Hong Kong', phone: '852' },
  {
    name: 'HM',
    label: 'Heard Island and McDonald Islands',
    phone: '672',
  },
  { name: 'HN', label: 'Honduras', phone: '504' },
  { name: 'HR', label: 'Croatia', phone: '385' },
  { name: 'HT', label: 'Haiti', phone: '509' },
  { name: 'HU', label: 'Hungary', phone: '36' },
  { name: 'ID', label: 'Indonesia', phone: '62' },
  { name: 'IE', label: 'Ireland', phone: '353' },
  { name: 'IL', label: 'Israel', phone: '972' },
  { name: 'IM', label: 'Isle of Man', phone: '44' },
  { name: 'IN', label: 'India', phone: '91' },
  {
    name: 'IO',
    label: 'British Indian Ocean Territory',
    phone: '246',
  },
  { name: 'IQ', label: 'Iraq', phone: '964' },
  {
    name: 'IR',
    label: 'Iran, Islamic Republic of',
    phone: '98',
  },
  { name: 'IS', label: 'Iceland', phone: '354' },
  { name: 'IT', label: 'Italy', phone: '39' },
  { name: 'JE', label: 'Jersey', phone: '44' },
  { name: 'JM', label: 'Jamaica', phone: '1-876' },
  { name: 'JO', label: 'Jordan', phone: '962' },
  {
    name: 'JP',
    label: 'Japan',
    phone: '81',
    suggested: true,
  },
  { name: 'KE', label: 'Kenya', phone: '254' },
  { name: 'KG', label: 'Kyrgyzstan', phone: '996' },
  { name: 'KH', label: 'Cambodia', phone: '855' },
  { name: 'KI', label: 'Kiribati', phone: '686' },
  { name: 'KM', label: 'Comoros', phone: '269' },
  {
    name: 'KN',
    label: 'Saint Kitts and Nevis',
    phone: '1-869',
  },
  {
    name: 'KP',
    label: "Korea, Democratic People's Republic of",
    phone: '850',
  },
  { name: 'KR', label: 'Korea, Republic of', phone: '82' },
  { name: 'KW', label: 'Kuwait', phone: '965' },
  { name: 'KY', label: 'Cayman Islands', phone: '1-345' },
  { name: 'KZ', label: 'Kazakhstan', phone: '7' },
  {
    name: 'LA',
    label: "Lao People's Democratic Republic",
    phone: '856',
  },
  { name: 'LB', label: 'Lebanon', phone: '961' },
  { name: 'LC', label: 'Saint Lucia', phone: '1-758' },
  { name: 'LI', label: 'Liechtenstein', phone: '423' },
  { name: 'LK', label: 'Sri Lanka', phone: '94' },
  { name: 'LR', label: 'Liberia', phone: '231' },
  { name: 'LS', label: 'Lesotho', phone: '266' },
  { name: 'LT', label: 'Lithuania', phone: '370' },
  { name: 'LU', label: 'Luxembourg', phone: '352' },
  { name: 'LV', label: 'Latvia', phone: '371' },
  { name: 'LY', label: 'Libya', phone: '218' },
  { name: 'MA', label: 'Morocco', phone: '212' },
  { name: 'MC', label: 'Monaco', phone: '377' },
  {
    name: 'MD',
    label: 'Moldova, Republic of',
    phone: '373',
  },
  { name: 'ME', label: 'Montenegro', phone: '382' },
  {
    name: 'MF',
    label: 'Saint Martin (French part)',
    phone: '590',
  },
  { name: 'MG', label: 'Madagascar', phone: '261' },
  { name: 'MH', label: 'Marshall Islands', phone: '692' },
  {
    name: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
    phone: '389',
  },
  { name: 'ML', label: 'Mali', phone: '223' },
  { name: 'MM', label: 'Myanmar', phone: '95' },
  { name: 'MN', label: 'Mongolia', phone: '976' },
  { name: 'MO', label: 'Macao', phone: '853' },
  {
    name: 'MP',
    label: 'Northern Mariana Islands',
    phone: '1-670',
  },
  { name: 'MQ', label: 'Martinique', phone: '596' },
  { name: 'MR', label: 'Mauritania', phone: '222' },
  { name: 'MS', label: 'Montserrat', phone: '1-664' },
  { name: 'MT', label: 'Malta', phone: '356' },
  { name: 'MU', label: 'Mauritius', phone: '230' },
  { name: 'MV', label: 'Maldives', phone: '960' },
  { name: 'MW', label: 'Malawi', phone: '265' },
  { name: 'MX', label: 'Mexico', phone: '52' },
  { name: 'MY', label: 'Malaysia', phone: '60' },
  { name: 'MZ', label: 'Mozambique', phone: '258' },
  { name: 'NA', label: 'Namibia', phone: '264' },
  { name: 'NC', label: 'New Caledonia', phone: '687' },
  { name: 'NE', label: 'Niger', phone: '227' },
  { name: 'NF', label: 'Norfolk Island', phone: '672' },
  { name: 'NG', label: 'Nigeria', phone: '234' },
  { name: 'NI', label: 'Nicaragua', phone: '505' },
  { name: 'NL', label: 'Netherlands', phone: '31' },
  { name: 'NO', label: 'Norway', phone: '47' },
  { name: 'NP', label: 'Nepal', phone: '977' },
  { name: 'NR', label: 'Nauru', phone: '674' },
  { name: 'NU', label: 'Niue', phone: '683' },
  { name: 'NZ', label: 'New Zealand', phone: '64' },
  { name: 'OM', label: 'Oman', phone: '968' },
  { name: 'PA', label: 'Panama', phone: '507' },
  { name: 'PE', label: 'Peru', phone: '51' },
  { name: 'PF', label: 'French Polynesia', phone: '689' },
  { name: 'PG', label: 'Papua New Guinea', phone: '675' },
  { name: 'PH', label: 'Philippines', phone: '63' },
  { name: 'PK', label: 'Pakistan', phone: '92' },
  { name: 'PL', label: 'Poland', phone: '48' },
  {
    name: 'PM',
    label: 'Saint Pierre and Miquelon',
    phone: '508',
  },
  { name: 'PN', label: 'Pitcairn', phone: '870' },
  { name: 'PR', label: 'Puerto Rico', phone: '1' },
  {
    name: 'PS',
    label: 'Palestine, State of',
    phone: '970',
  },
  { name: 'PT', label: 'Portugal', phone: '351' },
  { name: 'PW', label: 'Palau', phone: '680' },
  { name: 'PY', label: 'Paraguay', phone: '595' },
  { name: 'QA', label: 'Qatar', phone: '974' },
  { name: 'RE', label: 'Reunion', phone: '262' },
  { name: 'RO', label: 'Romania', phone: '40' },
  { name: 'RS', label: 'Serbia', phone: '381' },
  { name: 'RU', label: 'Russian Federation', phone: '7' },
  { name: 'RW', label: 'Rwanda', phone: '250' },
  { name: 'SA', label: 'Saudi Arabia', phone: '966' },
  { name: 'SB', label: 'Solomon Islands', phone: '677' },
  { name: 'SC', label: 'Seychelles', phone: '248' },
  { name: 'SD', label: 'Sudan', phone: '249' },
  { name: 'SE', label: 'Sweden', phone: '46' },
  { name: 'SG', label: 'Singapore', phone: '65' },
  { name: 'SH', label: 'Saint Helena', phone: '290' },
  { name: 'SI', label: 'Slovenia', phone: '386' },
  {
    name: 'SJ',
    label: 'Svalbard and Jan Mayen',
    phone: '47',
  },
  { name: 'SK', label: 'Slovakia', phone: '421' },
  { name: 'SL', label: 'Sierra Leone', phone: '232' },
  { name: 'SM', label: 'San Marino', phone: '378' },
  { name: 'SN', label: 'Senegal', phone: '221' },
  { name: 'SO', label: 'Somalia', phone: '252' },
  { name: 'SR', label: 'Suriname', phone: '597' },
  { name: 'SS', label: 'South Sudan', phone: '211' },
  {
    name: 'ST',
    label: 'Sao Tome and Principe',
    phone: '239',
  },
  { name: 'SV', label: 'El Salvador', phone: '503' },
  {
    name: 'SX',
    label: 'Sint Maarten (Dutch part)',
    phone: '1-721',
  },
  {
    name: 'SY',
    label: 'Syrian Arab Republic',
    phone: '963',
  },
  { name: 'SZ', label: 'Swaziland', phone: '268' },
  {
    name: 'TC',
    label: 'Turks and Caicos Islands',
    phone: '1-649',
  },
  { name: 'TD', label: 'Chad', phone: '235' },
  {
    name: 'TF',
    label: 'French Southern Territories',
    phone: '262',
  },
  { name: 'TG', label: 'Togo', phone: '228' },
  { name: 'TH', label: 'Thailand', phone: '66' },
  { name: 'TJ', label: 'Tajikistan', phone: '992' },
  { name: 'TK', label: 'Tokelau', phone: '690' },
  { name: 'TL', label: 'Timor-Leste', phone: '670' },
  { name: 'TM', label: 'Turkmenistan', phone: '993' },
  { name: 'TN', label: 'Tunisia', phone: '216' },
  { name: 'TO', label: 'Tonga', phone: '676' },
  { name: 'TR', label: 'Turkey', phone: '90' },
  {
    name: 'TT',
    label: 'Trinidad and Tobago',
    phone: '1-868',
  },
  { name: 'TV', label: 'Tuvalu', phone: '688' },
  {
    name: 'TW',
    label: 'Taiwan',
    phone: '886',
  },
  {
    name: 'TZ',
    label: 'United Republic of Tanzania',
    phone: '255',
  },
  { name: 'UA', label: 'Ukraine', phone: '380' },
  { name: 'UG', label: 'Uganda', phone: '256' },
  {
    name: 'US',
    label: 'United States',
    phone: '1',
    suggested: true,
  },
  { name: 'UY', label: 'Uruguay', phone: '598' },
  { name: 'UZ', label: 'Uzbekistan', phone: '998' },
  {
    name: 'VA',
    label: 'Holy See (Vatican City State)',
    phone: '379',
  },
  {
    name: 'VC',
    label: 'Saint Vincent and the Grenadines',
    phone: '1-784',
  },
  { name: 'VE', label: 'Venezuela', phone: '58' },
  {
    name: 'VG',
    label: 'British Virgin Islands',
    phone: '1-284',
  },
  {
    name: 'VI',
    label: 'US Virgin Islands',
    phone: '1-340',
  },
  { name: 'VN', label: 'Vietnam', phone: '84' },
  { name: 'VU', label: 'Vanuatu', phone: '678' },
  { name: 'WF', label: 'Wallis and Futuna', phone: '681' },
  { name: 'WS', label: 'Samoa', phone: '685' },
  { name: 'XK', label: 'Kosovo', phone: '383' },
  { name: 'YE', label: 'Yemen', phone: '967' },
  { name: 'YT', label: 'Mayotte', phone: '262' },
  { name: 'ZA', label: 'South Africa', phone: '27' },
  { name: 'ZM', label: 'Zambia', phone: '260' },
  { name: 'ZW', label: 'Zimbabwe', phone: '263' },
];

export default world;
